const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    name: "Drawn Angelic Top",
    price: 125,
    image: "/images/clothes/shirt1.png",
    company: "GWACH Atelier FW 2024",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recEHmzvupvT8ZONH",
    name: "Fur Collar Polo",
    price: 160,
    image: "/images/clothes/shirt5.png",
    company: "Vero Moda",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "rec5NBwZ5zCD9nfF0",
    name: "Black Pin-Pleated Denims",
    price: 120,
    image: "/images/clothes/shirt6.png",
    company: "Only",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Casual",
    amount: 1,
    stock: 4,
  },
  {
    id: "recd1jIVIEChmiwhe",
    name: "Black Infiity Trousers",
    price: 170,
    image: "/images/clothes/vest2.png",
    company: "Vero Moda",
    description:"Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoM2MyHJGHLVi5l",
    name: "Star Varity Style Jacket",
    price: 180,
    image: "/images/clothes/jacket1.png",
    company: "Only",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection. This Features Start patches on the elblows and a lining inside finish.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recotY5Nh00DQFdkm",
    name: "Parachute Pants",
    price: 120,
    image: "/images/clothes/pant4.png",
    company: "GWACH Atelier SS 2025",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "rec1Ntk7siEEW9ha1",
    name: "Waxed Denim Bustier Top",
    price: 90,
    image: "/images/clothes/pant7.png",
    company: "Only",
    description:"Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    company: "GWACH Atelier FW 2025",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "recNZ0koOqEmilmoz",
    name: "Polor Bear Fuax Fur Helment",
    price: 200,
    image: "/images/clothes/hat1.png",
    company: "GWACH Atelier",
    description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "recrfxv3EwpvJwvjq",
    name: "Parachute Pinched Pants",
    price: 100,
    image: "/images/clothes/pant7.png",
    company: "GWACH Atelier FW 2025",
    description:
      "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoW8ecgjtKx2Sj2",
    name: "Americana Dress Shirt",
    price: 90,
    image: "/images/clothes/pant6.png",
    company: "GWACH Atelier SS 2025",
    description:
      "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
    category: "Casual",
    amount: 1,
    stock: 5,
  },
];
export default data;
