const data = [
	{
	  id: "recd1jIVIEChmiwhe",
	  name: "Holster Vest",
	  price: 110,
	  image: "/images/clothes/vest2.png",
	  company: "GWACH 2024",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "vest",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recjjjIsdfsdwhe",
	  name: "Holster Vest",
	  price: 110,
	  image: "/images/clothes/vest3.png",
	  company: "GWACH 20204",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "vest",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recskhfw38392x2Sj2",
	  name: "Transparent Sling Bag",
	  price: 90,
	  image: "/images/clothes/bag1.png",
	  company: "GWACH Atelier SS 2025",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "bag",
	  amount: 1,
	  stock: 5,
	},
	{
	  id: "recjjjIsd234whe",
	  name: "Lepoard Print Tie",
	  price: 50,
	  image: "/images/clothes/tie1.png",
	  company: "GWACH 20204",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "tie",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recNZ0koOqEmilmoz",
	  name: "Polor Fur Helment",
	  price: 90,
	  image: "/images/clothes/hat1.png",
	  company: "GWACH Atelier",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "hat",
	  shipping: true,
	  amount: 1,
	  stock: 3,
	},
	{
	  id: "rec34857vbfeoz",
	  name: "Grizzly Fur Helment",
	  price: 90,
	  image: "/images/clothes/hat4.png",
	  company: "GWACH Atelier",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "hat",
	  shipping: true,
	  amount: 1,
	  stock: 3,
	},
	{
	  id: "recNZ0ko4353olmoz",
	  name: "Panther Fur Helment",
	  price: 90,
	  image: "/images/clothes/hat3.png",
	  company: "GWACH Atelier",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "hat",
	  shipping: true,
	  amount: 1,
	  stock: 3,
	},
	{
	  id: "recEHmzvupvT8ZONH",
	  name: "Fur Collar Polo",
	  price: 95,
	  image: "/images/clothes/shirt5.png",
	  company: "GWACH",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "shirt",
	  shipping: true,
	  amount: 1,
	  stock: 6,
	},
	{
	  id: "rec5NBwZ5zCD9nfF0",
	  name: "Leather Bustle Denimns",
	  price: 150,
	  image: "/images/clothes/pant3.png",
	  company: "GWACH",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "pant",
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recoM2MyHJGHLVi5l",
	  name: "Star Varity Jacket",
	  price: 180,
	  image: "/images/clothes/jacket1.png",
	  company: "Only",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection. This Features Start patches on the elblows and a lining inside finish.",
	  category: "jacket",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recotY5Nh00DQFdkm",
	  name: "Parachute Pants",
	  price: 100,
	  image: "/images/clothes/pant4.png",
	  company: "GWACH Atelier SS 2025",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "pant",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "rec1Ntk7siEEW9ha1",
	  name: "Cropped Hoodie ",
	  price: 95,
	  image: "/images/clothes/hoodie1.png",
	  company: "GWACH Atelier FW 2025",
	  description: "Crafted from premium 400 GSM fabics, our latest piece embodies the quality and rebellionous spirit of GWACH's Fall 24 collection.",
	  category: "hoodie",
	  shipping: true,
	  amount: 1,
	  stock: 2,
	},
	{
	  id: "recrfxv3EwpvJwvjq",
	  name: "Pin-Pleated Bustle Denims",
	  price: 170,
	  image: "/images/clothes/pant1.png",
	  company: "GWACH Atelier FW 2025",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "pant",
	  shipping: true,
	  amount: 1,
	  stock: 4,
	},
	{
	  id: "recoW8ecgjtKx2Sj2",
	  name: "Americana Button Up",
	  price: 85,
	  image: "/images/clothes/shirt6.png",
	  company: "GWACH Atelier SS 2025",
	  description: "Crafted from premium fabrics, our latest piece embodies the rebellious spirit of GWACH's Fall 24 collection.",
	  category: "shirt",
	  amount: 1,
	  stock: 5,
	},
  ];
  export default data;